allowBuilds:
  sharp: true
minimumReleaseAgeExclude:
  - '@next/env@16.2.11'
  - '@next/swc-darwin-arm64@16.2.11'
  - '@next/swc-darwin-x64@16.2.11'
  - '@next/swc-linux-arm64-gnu@16.2.11'
  - '@next/swc-linux-arm64-musl@16.2.11'
  - '@next/swc-linux-x64-gnu@16.2.11'
  - '@next/swc-linux-x64-musl@16.2.11'
  - '@next/swc-win32-arm64-msvc@16.2.11'
  - '@next/swc-win32-x64-msvc@16.2.11'
  - next@16.2.11
  - prettier@3.9.6
  - react-dom@19.2.8
  - react@19.2.8
